package FirGear.com.Entity;

import FirGear.com.Models.RegisterModel;
import com.mongodb.lang.NonNull;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Represents the user registration entity in the MongoDB database.
 * This entity is used to store user registration data like full name, email address, and password.
 *
 * @Entity RegisterEntity
 * @Document defines this class as a MongoDB document, and it will be mapped to the "register" collection.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "register") // Specifies the MongoDB collection where the document will be stored
public class RegisterEntity {

    /**
     * The unique identifier for each registered user, generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The full name of the user.
     * This field is required and cannot be null.
     */
    @NonNull
    private String fullName;

    /**
     * The email address of the user.
     * This field is required and cannot be null.
     */
    @NonNull
    private String emailAddress;

    /**
     * The password of the user.
     * This field is required and cannot be null.
     */
    @NonNull
    private String password;

    /**
     * Maps the fields from a RegisterModel to the RegisterEntity.
     * This method is used to populate the entity with user registration data.
     *
     * @param registerModel the RegisterModel containing the user input data
     */
    public void saveAll(RegisterModel registerModel) {
        this.fullName = registerModel.getFullName();
        this.emailAddress = registerModel.getEmailAddress();
        this.password = registerModel.getPassword();
    }


}
